//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary.Service.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Dictionary.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string addDataFail {
            get {
                return ResourceManager.GetString("addDataFail", resourceCulture);
            }
        }
        
        public static string addDataSuccess {
            get {
                return ResourceManager.GetString("addDataSuccess", resourceCulture);
            }
        }
        
        public static string deleteDataFail {
            get {
                return ResourceManager.GetString("deleteDataFail", resourceCulture);
            }
        }
        
        public static string deleteDataSuccess {
            get {
                return ResourceManager.GetString("deleteDataSuccess", resourceCulture);
            }
        }
        
        public static string editDataFail {
            get {
                return ResourceManager.GetString("editDataFail", resourceCulture);
            }
        }
        
        public static string editDataSuccess {
            get {
                return ResourceManager.GetString("editDataSuccess", resourceCulture);
            }
        }
        
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        public static string getDataSuccess {
            get {
                return ResourceManager.GetString("getDataSuccess", resourceCulture);
            }
        }
        
        public static string msgExistEmail {
            get {
                return ResourceManager.GetString("msgExistEmail", resourceCulture);
            }
        }
        
        public static string msgExistPhone {
            get {
                return ResourceManager.GetString("msgExistPhone", resourceCulture);
            }
        }
        
        public static string noData {
            get {
                return ResourceManager.GetString("noData", resourceCulture);
            }
        }
        
        public static string noReturnData {
            get {
                return ResourceManager.GetString("noReturnData", resourceCulture);
            }
        }
        
        public static string signupSuccess {
            get {
                return ResourceManager.GetString("signupSuccess", resourceCulture);
            }
        }
    }
}
